##############################################################################
# GitHub Actions Workflow for building Easy3D on Windows, Ubuntu, and macOS
# Copyright (C) 2022 Liangliang Nan <liangliang.nan@gmail.com>
# Licensed under GNU LGPL-v3 (see the LICENCE file)
##############################################################################
name: Test Build Easy3D

on: [push, pull_request]

jobs:
  build:
    name: "Build on ${{ matrix.platform }} - ${{ matrix.build_type }}"
    strategy:
          fail-fast: false
          matrix:
            platform: [Windows, Ubuntu, macOS]
            build_type: [Release]
    runs-on: "${{ matrix.platform }}-latest"
    steps:
      - uses: actions/checkout@v1
      - if: ${{ matrix.platform == 'Ubuntu' }}
        name: Create Build Environment
        run: sudo apt-get update || true;
             sudo apt-get install libgl1-mesa-dev mesa-common-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev;
      - if: ${{ matrix.platform == 'Ubuntu' || matrix.platform == 'MacOS' }}
        name: Make
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
      - if: ${{ matrix.platform == 'Windows' }}
        name: Make
        run: mkdir build && cd build && cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release .. && make
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build_${{ matrix.platform }}
          path: ${{ github.workspace }}/build
